/* web_pages.c - embedded web page for the softap component */
#include "web_pages.h"

const char index_html[] =
    "<!DOCTYPE html>\n"
    "<html>\n"
    "<head>\n"
      "<meta charset='utf-8'>\n"
      "<meta name='viewport' content='width=device-width,initial-scale=1'>\n"
      "<title>TinyWhoop Joystick</title>\n"
      "<style>\n"
        "html, body { height: 100%; margin: 0; }\n"
        "body { font-family: Arial, Helvetica, sans-serif; display: flex; flex-direction: column; background: #f5f5f5; color: #222; }\n"
        ".joy-container { flex: 1; display: flex; align-items: center; justify-content: center; gap: 24px; padding: 12px; box-sizing: border-box; }\n"
        ".joy-area { width: min(40vmin, 360px); height: min(40vmin, 360px); border-radius: 50%; background: radial-gradient(circle at 30% 30%, #eee, #ddd); position: relative; touch-action: none; user-select: none; display: flex; align-items: center; justify-content: center; box-shadow: 0 4px 10px rgba(0,0,0,0.15); }\n"
        ".knob { width: 18%; max-width: 72px; aspect-ratio: 1/1; border-radius: 50%; background: #ff6b6b; box-shadow: 0 2px 6px rgba(0,0,0,0.3); position: absolute; transform: translate(-50%,-50%); left: 50%; top: 50%; transition: background 0.08s; }\n"
        ".coords { font-size: 14px; text-align: center; }\n"
      "</style>\n"
    "</head>\n"
    "<body>\n"
      "<h1 style='text-align:center;margin:8px 0;'>Dual Joysticks</h1>\n"
      "<div class='joy-container'>\n"
        "<div id='joy1area' class='joy-area' role='application' aria-label='Joystick 1'>\n"
          "<div id='joy1knob' class='knob'></div>\n"
          "<div class='coords' style='position:absolute;bottom:8px;left:50%;transform:translateX(-50%);'>X: <span id='joy1x'>0.00</span> Y: <span id='joy1y'>0.00</span></div>\n"
        "</div>\n"
        "<div id='joy2area' class='joy-area' role='application' aria-label='Joystick 2'>\n"
          "<div id='joy2knob' class='knob'></div>\n"
          "<div class='coords' style='position:absolute;bottom:8px;left:50%;transform:translateX(-50%);'>X: <span id='joy2x'>0.00</span> Y: <span id='joy2y'>0.00</span></div>\n"
        "</div>\n"
      "</div>\n"
      "<script>\n"
        "(function(){\n"
          "let ws = null;\n"
          "function initWS(){ try{ ws = new WebSocket('ws://' + location.host + '/ws'); ws.onopen = function(){ console.log('ws open'); }; ws.onmessage = function(e){ console.log('ws msg', e.data); }; ws.onclose = function(){ console.log('ws close'); setTimeout(initWS,1000); }; ws.onerror = function(){ /* ignore */ }; }catch(e){ setTimeout(initWS,1000); } }\n"
          "let _lastSend = 0;\n"
          "function sendToServer(payload){ const now = Date.now(); if (now - _lastSend < 50) return; _lastSend = now; if(ws && ws.readyState===1){ try{ ws.send(JSON.stringify(payload)); return; }catch(e){} } /* fallback: send only first joystick as before */ try{ if(payload && payload.j1){ const p = payload.j1; fetch('/joy', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({x:p.x,y:p.y}), keepalive:true}); } }catch(e){} }\n"
          "function makeJoystick(prefix, onUpdate){ const area = document.getElementById(prefix+'area'); const knob = document.getElementById(prefix+'knob'); const xEl = document.getElementById(prefix+'x'); const yEl = document.getElementById(prefix+'y'); if(!area){ console.log('makeJoystick: area not found for', prefix); return { area:null, knob:null }; } console.log('makeJoystick: attached to', prefix); let active=false; let center={x:0,y:0}; function rect(){return area.getBoundingClientRect();} function getMaxDist(){const r=rect(); return (r.width/2) - (knob.offsetWidth/2);} function updateCenter(){const r=rect(); center = {x: r.left + r.width/2, y: r.top + r.height/2};} function handlePointer(evt){ evt.preventDefault(); const px = ('clientX' in evt) ? evt.clientX : (evt.touches && evt.touches[0] && evt.touches[0].clientX); const py = ('clientY' in evt) ? evt.clientY : (evt.touches && evt.touches[0] && evt.touches[0].clientY); if(px==null||py==null) return; const dx = px - center.x; const dy = py - center.y; const dist = Math.hypot(dx,dy); const angle = Math.atan2(dy,dx); const maxDist = getMaxDist() || 1; const limited = Math.min(dist, maxDist); const nx = Math.cos(angle)*limited; const ny = Math.sin(angle)*limited; const posX = (rect().width/2) + nx; const posY = (rect().height/2) + ny; knob.style.left = posX + 'px'; knob.style.top = posY + 'px'; const normX = (nx / maxDist); const normY = (ny / maxDist); if(xEl) xEl.textContent = normX.toFixed(2); if(yEl) yEl.textContent = normY.toFixed(2); if(onUpdate) onUpdate({x: normX, y: normY}); } function start(e){ active=true; updateCenter(); if(e.pointerId && area.setPointerCapture) area.setPointerCapture(e.pointerId); handlePointer(e); knob.style.background='#ff4b4b'; console.log('joystick', prefix, 'start'); } function move(e){ if(!active) return; handlePointer(e);} function end(e){ active=false; const r=rect(); knob.style.left = (r.width/2) + 'px'; knob.style.top = (r.height/2) + 'px'; if(xEl) xEl.textContent='0.00'; if(yEl) yEl.textContent='0.00'; if(onUpdate) onUpdate({x:0,y:0}); knob.style.background='#ff6b6b'; console.log('joystick', prefix, 'end'); } area.addEventListener('pointerdown', start); area.addEventListener('pointermove', move); area.addEventListener('pointerup', end); area.addEventListener('pointercancel', end); area.addEventListener('touchstart', start, {passive:false}); area.addEventListener('touchmove', move, {passive:false}); area.addEventListener('touchend', end); area.addEventListener('touchcancel', end); window.addEventListener('resize', updateCenter); updateCenter(); return { area, knob }; }\n"
          "window.addEventListener('load', function(){ initWS(); /* create two joysticks */ const j1 = makeJoystick('joy1', function(val){ /* send both joystick states together if possible */ window.jstate = window.jstate || {}; window.jstate.j1 = val; sendToServer(window.jstate); }); const j2 = makeJoystick('joy2', function(val){ window.jstate = window.jstate || {}; window.jstate.j2 = val; /* do not send fallback POST for j2 to keep server compatibility */ sendToServer(window.jstate); }); });\n"
        "})();\n"
      "</script>\n"
    "</body>\n"
    "</html>\n";
